version: "3.7"

services:
  # --- سرویس فرانت‌اند ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        API_URL: https://panel.doctorsoal.com/api
    container_name: doctorsoal_frontend
    restart: unless-stopped
    ports:
      - 3000:80
    networks:
      - doctorsoal_network

  # --- سرویس بک‌اند ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doctorsoal_backend
    restart: unless-stopped
    networks:
      - doctorsoal_network
    env_file:
      - ./backend/.env.production
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - DB_CONNECTION=pg
      - PG_HOST=doctorsoal_postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=zkw8gxy1qga.BGZ6qzv
      - PG_DB_NAME=doctorsoal
    volumes:
      - ./backend/tmp:/app/tmp
    depends_on:
      - postgres

  # --- سرویس دیتابیس ---
  postgres:
    image: postgres:14 # استفاده از نسخه 14 برای جلوگیری از مشکلات ناسازگاری
    container_name: doctorsoal_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zkw8gxy1qga.BGZ6qzv
      - POSTGRES_DB=doctorsoal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doctorsoal_network

# --- تعریف ولوم‌ها ---
volumes:
  postgres_data:
    name: doctorsoal_postgres_data

# --- تعریف شبکه‌ها ---
networks:
  doctorsoal_network:
    external: true
