version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
        API_URL: http://localhost:3333
    image: doctorsoal_frontend:latest
    container_name: doctorsoal_frontend
    ports:
      - "3100:3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:3333

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: doctorsoal_backend:latest
    container_name: doctorsoal_backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - app_network
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=rH552sQ6DDyRt7c2_Qd1Rr9HII4Km3MQ
      - DRIVE_DISK=local
      - DB_CONNECTION=pg
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=doctorsoal
      - PG_DB_NAME=doctorsoal
      - N8N_WEBHOOK_URL=https://n8n.hamyar.ai/webhook/f360f7e9-2fc3-4ecc-9e35-4e5bd371752c
    volumes:
      - ./backend/tmp:/app/tmp

  postgres:
    image: postgres:14
    container_name: doctorsoal_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=doctorsoal
      - POSTGRES_DB=doctorsoal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
