version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: doctorsoal_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zkw8gxy1qga.BGZ6qzv
      POSTGRES_DB: doctorsoal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doctorsoal_backend
    environment:
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: production
      APP_KEY: rH552sQ6DDyRt7c2_Qd1Rr9HII4Km3MQ
      APP_NAME: DoctorSoal
      DRIVE_DISK: local
      DB_CONNECTION: pg
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: zkw8gxy1qga.BGZ6qzv
      PG_DB_NAME: doctorsoal
      N8N_WEBHOOK_URL: https://n8n.hamyar.ai/webhook
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: doctorsoal_frontend
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: doctorsoal_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: always

  certbot:
    image: certbot/certbot
    container_name: doctorsoal_certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - nginx

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
