version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        API_URL: https://panel.doctorsoal.com/api
    image: doctorsoal_frontend:latest
    container_name: doctorsoal_frontend
    ports:
      - "3100:3000"
    restart: unless-stopped
    networks:
      - postgres_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: doctorsoal_backend:latest
    container_name: doctorsoal_backend
    ports:
      - "3333:3333"
    restart: unless-stopped
    networks:
      - postgres_network
    env_file:
      - ./backend/.env.production
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - DB_CONNECTION=pg
      - PG_HOST=doctorsoal_postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=zkw8gxy1qga.BGZ6qzv
      - PG_DB_NAME=doctorsoal
    volumes:
      - ./backend/tmp:/app/tmp

networks:
  postgres_network:
    external: true
