name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /opt

            # بک‌آپ گرفتن از دیتابیس و فایل‌های مهم
            if [ -d "doctorsoal/backend/tmp" ]; then
              echo "Taking backup of important files..."
              mkdir -p /opt/backups/$(date +%Y%m%d)
              cp -r doctorsoal/backend/tmp /opt/backups/$(date +%Y%m%d)/
            fi

            # تنظیم SSH برای استفاده از Deploy Key
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/doctorsoal_deploy_key

            if [ ! -d "doctorsoal/.git" ]; then
              rm -rf doctorsoal
              GIT_SSH_COMMAND="ssh -i ~/.ssh/doctorsoal_deploy_key -o StrictHostKeyChecking=no" git clone git@github.com:rokinio/doctorsoal.git doctorsoal
            else
              cd doctorsoal
              GIT_SSH_COMMAND="ssh -i ~/.ssh/doctorsoal_deploy_key -o StrictHostKeyChecking=no" git fetch origin main
              git reset --hard origin/main
            fi

            cd /opt/doctorsoal

            # ایجاد پوشه‌های مورد نیاز
            mkdir -p backend/tmp
            chmod -R 777 backend/tmp

            # بازگردانی فایل‌های مهم از بک‌آپ
            if [ -d "/opt/backups/$(date +%Y%m%d)/tmp" ]; then
              echo "Restoring important files..."
              cp -r /opt/backups/$(date +%Y%m%d)/tmp/* backend/tmp/
            fi

            echo "Stopping all related containers"
            docker stop doctorsoal_frontend doctorsoal_backend doctorsoal_postgres || true
            docker rm doctorsoal_frontend doctorsoal_backend doctorsoal_postgres || true

            # اجرای داکر کامپوز با فایل تولید
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up --build -d

            echo "Checking container status"
            docker ps | grep doctorsoal

            # بازنشانی nginx برای اعمال تغییرات
            docker restart nginx

            echo "Deployment completed!"
