name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # مسیر پروژه خود را اینجا قرار دهید
            cd /opt/doctorsoal-gm

            # دریافت تغییرات جدید
            git fetch origin
            git reset --hard origin/main

            # راه‌اندازی مجدد با داکر کامپوز
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up --build -d

            # راه‌اندازی مجدد nginx
            docker restart nginx

            echo "Deployment completed!"
